spring:
  profiles:
    include:
      - common

---

spring:
  config:
    activate:
      on-profile: common
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      show_sql: false
      hibernate:
        format_sql: true
        use_sql_comments: true
  jackson:
    property-naming-strategy: SNAKE_CASE

custom:
  redis:
    host: localhost
    port: 6379


